### ISSUE TITLE
Beatsaver requests causing twitch bans

### ISSUE THREAD

**Issue by Axsparta** [hardcpp/BeatSaberPlus#11]
I know this isn't directly, or solely, an issue with BeatSaberPlus, but someone has been going around and requesting a map which has something along the lines of "I am 9 years old" as a title, causing the request system to type the song name in chat, which is then reported by said person, causing bans.
It's very much a problem and might be able to fixed by adding some sort of filter to not put out text like that in chat, at least not automatically.
Preferably that filter should be enabled by default since otherwise it could affect to people who didn't know about the issue in the first place.
Thanks for your time!

**Comment by hardcpp** [comment]
Addressed in the last release, SafeMode is enabled by default
