### ISSUE TITLE
LevelStarted/LevelEnded events don't trigger automatically until they're manually triggered once

### ISSUE THREAD

**Issue by TheBlackParrot** [hardcpp/BeatSaberPlus#14]
I've got a couple of events set up to automatically switch between a couple of OBS scenes depending on if I'm in the menu or playing a map. They won't automatically trigger until I manually trigger them once with the test button, after which point they work as expected. Occasionally leads to stuff like this happening.
https://www.twitch.tv/videos/1680963749?t=00h19m55s

**Comment by hardcpp** [comment]
Hello, thanks for the issue, could you include Game version & Mod version please?

**Comment by TheBlackParrot** [comment]
BS 1.26.0, BS+ 5.0.3

**Comment by hardcpp** [comment]
Last release include the fix
