### ISSUE TITLE
Restarting a map prevents LevelEnded events from triggering

### ISSUE THREAD

**Issue by TheBlackParrot** [hardcpp/BeatSaberPlus#15]
If I need to restart the map, I start the map over from the menu and avoid the Restart button in-game in order to have LevelEnded events trigger properly. If I use the Restart button, all LevelEnded events fail to trigger until I re-enter the map from the menu.
(forgot to clip this happening, sorry)

**Comment by hardcpp** [comment]
Hello, thanks for the issue, could you include Game version & Mod version please?

**Comment by TheBlackParrot** [comment]
BS 1.26.0, BS+ 5.0.3

**Comment by hardcpp** [comment]
It was related to the BeatSaber level restart mechanic. Fixed and pending next update deployment
