### ISSUE TITLE
Song Info Bugs - Name Mismatch / Panel stuck inside leaderboard.

### ISSUE THREAD

**Issue by Xentha** [hardcpp/BeatSaberPlus#22]
Unsure if this has already been reported elsewhere.

I've been unable to manually reproduce the name bug, but seemingly at random it will replace the name of a song in the list with another song. All other details remain correct.
With the panel misplacement, it seems there's like a 1 in 5 chance (more likely on the first time running after waking my computer from sleep) that when I start the game and go to the song list, the song details will be stuck inside the leaderboard and the only way to fix it is restarting the game.

I've included pictures of what this looks like.

Specs:
OS: Windows 10
CPU: Intel i5-10400F
GPU: AMD RX6750 XT
HMD: Quest 2
Connection: JSAUX Cable.
Game Version: 1.29.1 through Legacy Launcher.
BeatSaberPlus Version: 6.1.0

![Name Mismatch](https://github.com/hardcpp/BeatSaberPlus/assets/75454177/3a2fd4f6-90dd-4378-81b8-b242462257ab)
![Capture](https://github.com/hardcpp/BeatSaberPlus/assets/75454177/e4bd4d25-3d53-424a-ab0a-87520988fc16)

**Comment by iPixelGalaxy** [comment]
This is not a BS+ issue, this is a BSML issue that will not ever get addressed for 1.29.1, however you can fix the issue with this mod: https://github.com/denpadokei/FontNao-ru/releases

**Comment by Xentha** [comment]
Oh. I only thought because it started to show up after the big overhaul. That is highly unfortunate. Will that also fix the UI stuck in leaderboard problem?

**Comment by satyabss** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
StevenFarley, @anistark, @ParsaTech, @Doomjunky, @ousheobin, @zhongkai, @adityavs, @ethandrower, @volkanmetin, @zyuezheng, @nazuke, @andemengo, @tolgafiratoglu, @brapascal, @bjsunhe, @Pavel-Durov, @BRKalow, @myarth, @d6vio, @unicrn
