### ISSUE TITLE
$SongName variable in config writes bsr?

### ISSUE THREAD

**Issue by ACMDatabase** [hardcpp/BeatSaberPlus#26]
For me, the $SongName variable is writing the bsr code instead of the song title. Is there another variable I should use for song title? 

I'm testing it on the BSRCommand_RequestOK config line.

Ok so it seems that SongName and Author both becomes the bsr id instead of the song title and author.
And it is in beat saber 1.29.1 that it does not work. But it does work in beat saber 1.34.2.

**Comment by Flamebullet** [comment]
@ACMDatabase head into your `SteamLibrary\steamapps\common\Beat Saber\UserData\BeatSaberPlus\ChatRequest` folder and open up Config.json. On line 3 change `"SafeMode2": true,` to `"SafeMode2": false,` and it should fix it.
