### ISSUE TITLE
Mod Permissions Review

### ISSUE THREAD

**Issue by arielcosmelli** [hardcpp/BeatSaberPlus#29]
I think they went overboard with the basic permissions they request in this new version.
I would evaluate the following items.

- Manage your channel's broadcast settings, including updating channel settings and managing broadcast flags and tags.
- Assign or remove the moderator role to users on your channel
- Send whisper messages
- View your whisper messages
- Get a list of all subscribers to your channel and see if a user is subscribed

Greetings!

**Comment by hardcpp** [comment]
Hey thoses a sadly required to implement some of the twitch features. Everything run locally on your PC, so the token stay on the PC. The channel manage is to implement the /raid command in a next update
