### ISSUE TITLE
Twitch chat not showing up in game

### ISSUE THREAD

**Issue by yorgje** [hardcpp/BeatSaberPlus#4]
It seems like ChatCore is making the connection to my twitch channel alright, since !bsr populates the chat request queue, but messages posted in the chat don't appear in the in-game chatbox.

From my logs, I see errors like:

```
[ERROR @ 11:31:59 | BeatSaberPlus] An exception occurred in ChatMessageBuilder while parsing msg with 0 emotes. Msg: "asdf"
[ERROR @ 11:31:59 | BeatSaberPlus] System.NullReferenceException: Object reference not set to an instance of an object
[ERROR @ 11:31:59 | BeatSaberPlus]   at BeatSaberPlus.Modules.Chat.Utils.ChatMessageBuilder.PrepareImages (BeatSaberPlusChatCore.Interfaces.IChatMessage p_Message, BeatSaberPlus.Modules.Chat.Extensions.EnhancedFontInfo p_Font) [0x001b2] in <677367d7516a4c28a3ac0e48219da5f4>:0 
[ERROR @ 11:31:59 | BeatSaberPlus]   at BeatSaberPlus.Modules.Chat.Utils.ChatMessageBuilder+<BuildMessage>d__1.MoveNext () [0x00000] in <677367d7516a4c28a3ac0e48219da5f4>:0 
```

Some system info (lmk if anything else would be useful):
- BeatSaberPlus 2.0.12 (also saw the same behavior in 2.0.7)
- Ubuntu 20.04, running beat saber through Proton 5.13-4
- I'm using geefr's linux fork of BSIPA https://github.com/geefr/BSIPA-Linux

**Comment by yorgje** [comment]
never mind, figured it out! My Proton didn't have the Segoe UI font installed, but I put it in `~/.steam/steam/steamapps/compatdata/620980/pfx/drive_c/windows/Fonts` and now it's working

**Comment by hardcpp** [comment]
Hello, i'm glad to hear that you got it working on linux ! Is it simple to get it running ? if yes are you up to write some basic instructions that i can add to the ReadMe for others/futures users on linux ?

**Comment by yorgje** [comment]
Yeah it's really simple! Basically what I did was:

- Install Beataroni from here: https://github.com/geefr/beatsaber-linux-goodies (basically a linux version of modassistant)
- Through Beataroni, install the dependencies
- Download the `Segoe Ui` font from somewhere; I grabbed it using https://github.com/mrbvrz/segoe-ui-linux
- Move/copy the `segoeui.ttf` file into `~/.steam/steam/steamapps/compatdata/620980/pfx/drive_c/windows/Fonts` (not sure if the bold/italic/etc variants are necessary, but I copied them over too)

Then everything just works

**Comment by kittywitch** [comment]
Additionally:
* if you are using bs-manager or such, and you set your Proton directory manually, make sure you are using the same version referenced by the symlinks for the other fonts in `~/.local/share/Steam/steamapps/compatdata/620980/pfx/drive_c/windows/Fonts`
* for correctness, you might want to move them into the path referenced, e.g. `.local/share/Steam/steamapps/common/Proton Hotfix/files/share/wine/fonts` instead and symlink them into the compatdata pfx Fonts dir, like the other fonts that already were.
* If you install the fonts to the pfx itself without putting them in the correct Proton directory's fonts, they *will not load* and will not be found.

**Comment by Interpause** [comment]
For clarification, look inside your BSManager "Installation folder" in the settings page of BSManager. For me it was `~/BSManager/SharedContent/compatdata/pfx/drive_c/windows/Fonts/`.
