### ISSUE TITLE
Chat emotes do not show up in the game until the regular chat module is turned on once.

### ISSUE THREAD

**Issue by TheBlackParrot** [hardcpp/BeatSaberPlus#7]
I prefer using Desktop+ for chat rather than having it in-game with BeatSaberPlus. I do like the emote rains BeatSaberPlus provides, but I have to toggle the chat module first.

https://www.twitch.tv/videos/1056951907?t=7m45s

**Comment by hardcpp** [comment]
Thanks for the report, i'm gonna take a look

**Comment by hardcpp** [comment]
Fixed in upcomming 5.0.1
